[[snippets]]
prefix = "groot"
scope = [ "rust" ]
body = """
struct RootView;

impl Default for RootView {
    fn default() -> Self {
        RootView
    }
}

#[allow(unused)]
impl Render for RootView {
    fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {
        div()
    }
}

fn on_finish_launching(app: &mut App) {
    app.open_window(WindowOptions::default(), build_root_view);
}

#[allow(unused)]
fn build_root_view(window: &mut Window, app: &mut App) -> Entity<RootView> {
    app.new(|cx| RootView::default())
}
"""
description = "gpui RootView"

[[snippets]]
prefix = "gcustom"
scope = [ "rust" ]
body = """
pub fn ${1}(w: f32, h: f32) -> impl IntoElement {
    canvas(
        |_, _, _| {},
        move |bounds, (), window, _| {
            let Bounds { origin, size } = bounds;
            let mut lines = vec![];
            let mut builder = PathBuilder::fill();
            let path = builder.build().unwrap();
            lines.push((path, rgba(c)));
            for (path, color) in lines {
                window.paint_path(path, color);
            }
        },
    )
    .w(px(w))
    .h(px(h))
}
"""
description = "gpui CustomElement"
